namespace: apps

app:
  name: rest-quarkus-price-fruits
  deploymentName: rest-quarkus-price-fruits
  deploymentConfigMatch: "rest-quarkus-price-fruits"
  version: "v1"
  istio: "'false'"  
  persistentVolumeClaim:
    enabled: false

ingressgateway:
    enabled: false
    name: rest-quarkus-price-fruits-ingressgateway
    host: portal1-bff-app-referencia-dev.apps.ocp.sefaz.pe.gov.br
    selector: ingressgateway
    port:
      number: 80
      name: http
      protocol: HTTP  

virtualservice:
    enabled: false
    name: rest-quarkus-price-fruits-virtualservice
    gateway: rest-quarkus-price-fruits-ingressgateway
    destination:
      number: 9000
      host: portal-bff

configmap:
  enabled: false
#  items:
#    - name: redis-conf
#      filePath: "files/00-alpine.conf"
#      fileName: 00-alpine.conf

#secrets:
#  - name: portal-cache-funcionalidades-sb-secrets
#    keys:
#      - name: DB_PASS
#        value: "admin"
#        encoded: false
#      - name: USER_PASSWORD
#        value: "OCdcVWNjACcYBSwg"
#        encoded: false
#      - name: TRUST_STORE_PASSWORD
#        value: "password"
#  - name: datagrid-truststore-secret
#    keys:
#      - name: "truststore.jks"
#        encoded: true
#        value: "MIIFYgIBAzCCBQwGCSqGSIb3DQEHAaCCBP0EggT5MIIE9TCCBPEGCSqGSIb3DQEHBqCCBOIwggTeAgEAMIIE1wYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBRK0VorYErCKkefefmOt0Q8sDYiTAICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEORJFp4fRfhBEjx3Qx0F9eSAggRg+jdYu3laTEDdRVEtgdWNWkTTVTW4ZXg9WCNgFoz2oVuV6gxOfcvQ/M3dc7iT5A8BNft46mQCxNV0Ovstcu7mxZayov9wmQy8RW0om8OsoLHxtS7Hm/8qfQV4ItfaRPaRikG+yDHj+/+7ZuxgEusYpIZFT+YPzKqfDjKHzZGnMCpeI5EVznvcu6FVKKro2MCdop2uThkaYPrppLlOjfAN1QT6mSyTZY5V1Uvo066gYG4NoTLutZrS3FZjoiYC+hP4XMsE7KTKWS9E6pbedLI4KnX7tNP94qpO5v5IqpsF4c4o3DAQf4jaXihkr4Z2iSlGex2JPzhXV5yONgNI0ZZd0BvuUikBTmH2/YjMxHjr+3YrcBZetW172PDi+uUA0pGkQw6Wc59MTTCkI6Z/hmzbFgX3tmnJ+MVlNMjho72WTTiusNDt5ULYxVOKX/k/ztRNQj2QIDaGhZ0lFsZ7Ss21PliwYnEiTPdD9t1yRc1cTi/Z9QjJ2INAIijO+izTQE10Nwx2wsdV4dquSo32Tr5RcgrjWOn4QloRnz2MNqnzFfQBk5LtYIgmrD9abLKqs/I0SVULlu7kI96DG5Mils6U306NUIAMt5g8C6uqYhCn/yYG4CHbtGVTNOQKiYd/TxRGNsxnDO6+VdMHzEX86TgY/g1wV5/BNvGiegXuRL5JyGYNP6ZSJxX0kv0CfEJ9HFWg0Zh4urRNO4e6C14bh7MHoR7+SQtZlIF/X1MIdBP0Poz64RUIFoSZqDG0rPvIAQ52fYFn/ynweKS0PhtjM6dMeaKBh1imeHR37Wo5S+PUAA6RcJrIKzDcYyB13pK0HwYcxpi9bqmnbmOthl5NR+gcSlDGtjEr7wPxbVNEdom3TGCdnBA9/rcKlpgWUexroPYQglgzzuFPbI88TC5MYyogFeB+NbN/4TjGI5NCq9PeC9m85csfSiicnydZvs7YlyPYKnLf977yWiuepZrqpGjV+V1AxfKTyemZJ0EAkG3HRB1nyUahasWg9MZ0XO+B7FNXeEp9LFcAd2qEWHCoY4Pw3NzzbQhwlnosXz+VrR4G+tV8p3HPbM4kgYAt/bvzwlwuclpB/yA3PmK9WU2RYapD3jWKSG40Vuizxos8Q1kO+oWA3fAj8i7qfPVc8Qphik7soDOr2N03O1FHIkleewL0akq41iNlYvr/v+7n54HxUTmEm+U3yENlNx0imH6m2yUSjMGfg8/Rmbh5MfXHRqvxRIoCa1jJqaPE8ENLcPJchfZ9np9HWem1Cxpdk6BluNmcGXMs1naFWwPX0nqh/DDE0ND8jRFbH4YakwR7pkk+gSsqnsvfkqGbvl0vFe00e3d84AetUjzHeSrY9Hb0TAZi4KnInAKTRkW+lNSWZFlSdYeZmXWtVTEegyiq3WUsiix3lHLmDkn/YHh1vtUPkAO2ulHlt09uwoch0Al7R7g2I8okHroGpOXumiTtwj26kXYMPMAC6gphJ8DGhTBeNjjbxzBNMDEwDQYJYIZIAWUDBAIBBQAEIOXetNnmk+I3yKPRFQBxxOBnb2RTqry6lL0VTkAZ739UBBQOf5duyf5nYImELPcweVplYUawjAICJxA="


replicaCount: 1

image:
  name: image-registry.openshift-image-registry.svc:5000/apps/rest-quarkus-price-fruits@sha256:c8cba1bf845cca497c5b11352f9c6398f41cb3d84db25f295cf31084f2cae62d
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "rest-quarkus-price-fruits"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ports:
  - containerPort: 8080

#resources:
#  limits:
#    cpu: 600m
#    memory: 1Gi
#  requests:
#    cpu: 10m
#    memory: 128Mi

environments:
  - name: PORTAL_CRUD_HOST
    value: "http://portal-crud-funcionalidades.app-referencia-dev.svc.cluster.local"

# service
service:
  type: NodePort
  name: http
  port: 8080
  targetPort: 8080

route:
  host: rest-quarkus-price-fruits.apps.middleware.rhbr-lab.com
  termination: edge

#readinessProbe:
#  httpGet:
#    path: /actuator/health/readiness
#    port: 8081
#    scheme: HTTP
#  initialDelaySeconds: 20
#  timeoutSeconds: 5
#  periodSeconds: 10
#  successThreshold: 1
#  failureThreshold: 3

#livenessProbe:
#  httpGet:
#    path: /actuator/health/liveness
#    port: 8081
#    scheme: HTTP
#  initialDelaySeconds: 20
#  timeoutSeconds: 5
#  periodSeconds: 10
#  successThreshold: 1
#  failureThreshold: 3
